### PR TITLE
feat: remove non-wheel artifacts for PyPI publish

### PR DESCRIPTION
**Pull request by freedmand**
## Description

The beta release failed because the GitHub actions step that downloads artifacts and then uploads them to PyPI will upload ALL artifacts, even those from other jobs. We only want Wheel files to trickle through. We won't know if this works until we merge to dev

### CODE REVIEW

**Comment by chriszs** [comment]
Would it make any sense to upload the wheel artifact with a specific name, so you can download just that named artifact from with the download-artifact action instead of downloading all and then deleting some?

**Comment by freedmand** [comment]
It’s 6 different files. They have specific names tuned to the
OS/architecture combo. The commonality is the .whl. There are 13 other
files that get deleted and they’re approx 200-300kb each

**Comment by chriszs** [comment]
@freedmand I'm going by the docs, which seem to indicate you can name [supply a name](https://github.com/actions/upload-artifact#upload-an-individual-file) when you upload the artifacts and then [use that name](https://github.com/actions/download-artifact#download-all-artifacts) to download just that named artifact. I could be misinterpreting it, though.

**Comment by chriszs** [comment]
The artifact named "artifact," which is what you're downloading, is just the default name if no name is supplied at upload.

**Comment by freedmand** [comment]
Thanks, @chriszs, that makes sense. Let me know if this refactor looks good

**Review by chriszs — APPROVED** [review]

**Comment by chriszs** [comment]
Yes! Approved.

**Pull request merged**
